services:
  app: # Changed from 'php' to 'app' for clarity; more descriptive
    image: image-backend
    build:
      context: ./backend # Current directory
    container_name: test-app # Consistent naming
    working_dir: /var/www/html # Application's root directory
    volumes:
      - ./backend:/var/www/html # Mounts your application code; useful for development
      - vendor-volume:/var/www/html/vendor  # This will preserve the vendor directory which will not affect the host
    user: "${UID}:${GID}"
    networks:
      - app-network
    depends_on: # Define dependencies for startup order
      - postgres-db
    #  ports: # Removed ports.  Expose in nginx, not here.
    #    - "9000:9000" # PHP-FPM port;  No need to expose this to the host
  
  vue:
    image: image-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.vue
    container_name: test-frontend
    ports:
      - "5175:5174"  # Host port 5175 maps to container port 5174
    volumes:
    - ./frontend:/app
    - node_modules_vue:/app/node_modules
    networks:
      - app-network

  web: # Changed from 'nginx' to 'web'
    image: nginx:alpine # Lightweight Nginx image
    container_name: test-nginx # Consistent naming
    ports:
      - "8002:80" # Host:Container port mapping.  Use 8000 for local
    volumes:
      - ./backend:/var/www/html # Serve your application files
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf # Nginx configuration
    depends_on:
      - app # Depend on the 'app' service (PHP-FPM)
    networks:
      - app-network
    
 
  
  postgres-db:
    image: postgres:15
    container_name: test-postgres-db
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

    
  # mysql-db: # Using 'mysql-db' is fine, but 'database' is also common
  #   image: mysql:5.7 # Or a specific version
  #   container_name: laravue-docker-mysql-db # Consistent naming
  #   environment:
  #     MYSQL_ROOT_PASSWORD: secret # DO NOT USE 'secret' in production
  #     MYSQL_DATABASE: laravel #Should be in .env
  #     MYSQL_USER: laravel    #Should be in .env
  #     MYSQL_PASSWORD: secret # DO NOT USE 'secret' in production #Should be in .env
  #     #  MYSQL_TCP_PORT: 3306 # Explicitly set the port, though it defaults to 3306.
  #   volumes:
  #     - dbdata:/var/lib/mysql # Persist database data
  #   networks:
  #     - app-network
    #ports: #Do not expose the database port to the host
    #  - "3306:3306" # Only needed for direct access (e.g., with a client)

  # Add a phpmyadmin service only for development.  Do not use in production.
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: laravue-docker-phpmyadmin
  #   ports:
  #     - "8001:80"
  #   environment:
  #     PMA_HOST: mysql-db  # Connect to the 'mysql-db' service
  #     PMA_PORT: 3306
  #     PMA_ARBITRARY: 0 #Set to 0 for security
  #   depends_on:
  #     - mysql-db
  #   networks:
  #     - app-network
    
networks:
  app-network:
    driver: bridge # Default bridge network

volumes:
  vendor-volume:
    driver: local
  pgdata:
  node_modules_vue:
